[theme]
base = "light"
primaryColor = "#F59E0B"
backgroundColor = "#F8F7F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
